microlinkhq/youtube-dl-exec

src/index.js
test/args.js

Youtube-dl does not support `-foo=bar` styled single-character-flags.
This commit disables such styling completely, by using spaces instead of `=`

fix: single-character-flags with values are now supported

---

README.md

`dumpSingleJson` is equivalent to `--dump-single-json` instead of `--dump-json`
related: https://github.com/microlinkhq/youtube-dl-exec/issues/15

Fix Typo in Readme: dump-json->dump-single-json

---

src/constants.js

I want to use the `.npmrc` file to set `YOUTUBE_DL_HOST` and `YOUTUBE_DL_FILENAME`, these config can be accessed from `process.env.npm_config_<env>` for example: `process.env.npm_config_YOUTUBE_DL_FILENAME`.

feat: read npm_config environment variables

---

package.json

```
> youtube-dl-exec@1.2.11 check
> bin-version-check python '>=2'
Error: Invalid version range
```
This PR fix above mentioned issue, which cause error while installation.

Fix(windows): npm run check

---

README.md
src/constants.js

Starting with npm v7 `npm_config` environment variables from `.npmrc` or `npm config set <key> <value>` will always be lowercase in `process.env`

fix: npm_config environment variables on npm v7

---

src/index.d.ts

download archive command was not working because of a typo. It was 'dowloadArchive' missing an 'n'.

fix: typo error

---

package.json

This is still valid and will debug Windows users.
This will truly resolve https://github.com/microlinkhq/youtube-dl-exec/issues/112

Fix for Windows 10 / PowerShell Users

---

src/index.d.ts

Type addHeader is taking string array(Referenced from readme.md). Declared as string.
for example: 
```
const youtubedl = require('youtube-dl-exec')
youtubedl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
dumpSingleJson: true,
noCheckCertificates: true,
noWarnings: true,
preferFreeFormats: true,
addHeader: [
'referer:youtube.com',
'user-agent:googlebot'
]
}).then(output => console.log(output))
```

Updated wrong type for type addHeader.

---

src/index.d.ts

The existing Typescript defs weren't recognized as properties of the default export, so attempting to use them in a Typescript project cause an error.
add types for exec and create functions
As far as I can tell this is the only way to export the exec and create functions both as function properties and individual exports.

125 types for `exec` don't seem to be applied properly

---

package.json

- preinstall now checks for either python3 or python version being >= to 3.7

feat: preinstall check for python or python3 version >=3.7

---

src/index.d.ts

manifest_url is exist in formats response but not exist in typescript types.

Added missing response type manifest_url

---

README.md
package.json
src/index.js
test/error.js

Some `yt-dlp` errors were not being exposed because they were not being detected correctly.

feat: normalize errors

---

package.json
scripts/preinstall.mjs

It's more flexible and offer granular error handling than run a npx command wrapped by bash.
Closes https://github.com/microlinkhq/youtube-dl-exec/issues/142

feat: move preinstall command into a separate script

---

package.json

The current version (2.3.1) gives security warnings in npm:
```shell
% npm audit --production
npm WARN config production Use `--omit=dev` instead.
semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install bin-version-check@5.1.0, which is outside the stated dependency range
node_modules/semver-truncate/node_modules/semver
semver-truncate  <=2.0.0
Depends on vulnerable versions of semver
node_modules/semver-truncate
bin-version-check  2.1.0 - 5.0.0
Depends on vulnerable versions of semver-truncate
node_modules/bin-version-check
3 moderate severity vulnerabilities
To address all issues, run:
npm audit fix --force
```
After updating …

fix: update bin-version-check to remove security warnings

---

src/index.d.ts

When working on TypeScript projects, having the ability to import type definitions would be very convenient.

refactor(index.d.ts): exporting types

---

README.md
package.json
scripts/postinstall.js

Branched off #191
Swaps out `simple-get` for `fetch`, and uses streams instead of buffering the whole binary in memory.
```console
$ node ./scripts/postinstall.js
[youtube-dl-exec] Downloading `youtube-dl` binary
[youtube-dl-exec] Download Location: `/var/folders/(...)/T/yt-dl-exec-10fffb83`
[youtube-dl-exec] Ensuring directory exists: `/git/microlinkhq/youtube-dl-exec/bin`
[youtube-dl-exec] Moving binary to `/git/microlinkhq/youtube-dl-exec/bin/yt-dlp`
[youtube-dl-exec] Setting permissions for `/git/microlinkhq/youtube-dl-exec/bin/yt-dlp`
[youtube-dl-exec] Installation complete
```
Tested with `npm`, `yarn` and `pnpm`, and they all hide `std{out,err}` logs from post-install scripts on install unless the run fails. You can confirm this as well.

feat!: rewrite the postinstall script

---

src/index.js

Resolves #198. 
To match the typings file, a named export of `youtubeDl` is added

Update index.js to export youtubeDl

---

README.md

this should fix the issue where npm shows both copies of the image.
https://www.npmjs.com/package/youtube-dl-exec

fix: npm duplicate image

---

scripts/preinstall.mjs

latest version of yt-dlp (as of 2025-02-02) requires at least python 3.9

Update minium version requirement for Pyhton

---

package.json
scripts/preinstall.mjs

This pull request updates the bin-version-check package to resolve a deprecation warning. The package was deprecated due to a name change.

Fix: Update deprecated `bin-version-check` package due to name change
